### ISSUE TITLE
Current Python version (3.8.10) is not allowed by the project (^3.10)

### ISSUE THREAD

**Issue by jooooaah** [nextcloud/llm#13]
Hello folks,

Ubuntu 
Nextcloud Version: 27.1.2, llm: 1.0.2

python --version
Python 3.10.13

python-venv installed

occ throws:
```
Install dependencies for llm app
     - ERROR: Failed to install python dependencies: Failed to install python dependencies: PATH=/***/apps/llm/python/bin:$PATH VIRTUAL_ENV=/***/apps/llm/python POETRY_CACHE_DIR=/***/apps/llm/python/.cache /***/apps/llm/python/bin/poetry  install --no-root returned Current Python version (3.8.10) is not allowed by the project (^3.10).
Please change python executable via the "env use" command.
```

Any clues?

**Comment by marcelklehr** [comment]
It appears the app think the current python version is 3.8.10. Are you using docker?

**Comment by sksksksk** [comment]
same here while trying to update nextcloud from 27.1.2 to 27.1.3, which also updates the llm app to 1.1.0.

Update app llm from App Store
Repair step: Install dependencies for llm app
Repair error: Failed to install python dependencies: Failed to install python dependencies: PATH=/PATH_TO_NEXTCLOUD/apps/llm/python/bin:$PATH VIRTUAL_ENV=/PATH_TO_NEXTCLOUD/apps/llm/python POETRY_CACHE_DIR=/PATH_TO_NEXTCLOUD/apps/llm/python/.cache /PATH_TO_NEXTCLOUD/apps/llm/python/bin/poetry  install --no-root returned InvalidCurrentPythonVersionError

  Current Python version (3.9.2) is not allowed by the project (^3.10).
  Please change python executable via the "env use" command.

  at /PATH_TO_NEXTCLOUD/apps/llm/python/venvs/poetry/lib/python3.9/site-packages/poetry/utils/env/env_manager.py:447 in create_venv
      443│             current_python = Version.parse(
      444│                 ".".join(str(c) for c in env.version_info[:3])
      445│             )
      446│             if not self._poetry.package.python_constraint.allows(current_python):
    → 447│                 raise InvalidCurrentPythonVersionError(
      448│                     self._poetry.package.python_versions, str(current_python)
      449│                 )
      450│             return env
      451│

My platform is Debian 10, with PHP 8.2. No docker
/PATH_TO_NEXTCLOUD/apps/llm/python/bin/python --version 
indeed returns Python 3.9.2

**Comment by marcelklehr** [comment]
Well, I can't really help you with this. You need python 3.10.

**Comment by sksksksk** [comment]
as far as I understand, the python version is shipped with the llm app. Please checkout the path of the executable: 
/PATH_TO_NEXTCLOUD/apps/llm/python/bin

And if I indeed cd to this path, and execute `./python --version`  , i get
Python 3.9.2

So I understand that the llm app ships it's own python executable, which is in the wrong version. Am i missing something?

**Comment by marcelklehr** [comment]
The app sets up a venv in apps/llm/python which is why there's a python binary in there

**Comment by sksksksk** [comment]
ok. My knowledge with python is obviously very limited. I will look into updating my distribution's python version. Thanks!
