### ISSUE TITLE
when using sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ maintenance:repair

### ISSUE THREAD

**Issue by Plural0** [nextcloud/llm#15]
I get the below error in the logs and when I run sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ maintenance:repair

Install dependencies for llm app
     - ERROR: Failed to install python dependencies: Failed to install python dependencies: PATH=/var/www/html/custom_apps/llm/python/bin:$PATH VIRTUAL_ENV=/var/www/html/custom_apps/llm/python POETRY_CACHE_DIR=/var/www/html/custom_apps/llm/python/.cache /var/www/html/custom_apps/llm/python/bin/poetry  install --no-root returned Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing gpt4all (1.0.12)

  RuntimeError

  Unable to find installation candidates for gpt4all (1.0.12)

  at /var/www/html/custom_apps/llm/python/venvs/poetry/lib/python3.11/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│
       70│             links.append(link)
       71│
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│

**Comment by joshtrichards** [comment]
See requirements:

https://github.com/nextcloud/llm?tab=readme-ov-file#a-large-language-model-in-nextcloud
