### ISSUE TITLE
Remove canceled downloads and checksum downloaded models

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/llm#29]
Currently if a download fails or is canceled the file stays. Next time trying to download it nothing happens because the file is already present.
We should remove the downloaded file if the download was canceled.
We should check if the downloaded file matches a checksum and if not remove it.

**Comment by marcelklehr** [comment]
I think the [force flag](https://github.com/nextcloud/llm/blob/main/lib/Command/DownloadModels.php#L33) is good enough.

**Comment by provokateurin** [comment]
But there is no way to automatically or manually verify that the downloaded file is correct. So at least the checksum should be implemented.

**Comment by marcelklehr** [comment]
I disagree about the should, especially since your task is something else, as far as I can recall, but be my guest :shrug:

**Comment by provokateurin** [comment]
I know my task is something else, but I already spent a some time on other improvements. I opened an issue for this one because I didn't want to do it immediately. Just take it as a note that it might be nice to have for later
