### ISSUE TITLE
All tasks fail with error No module named 'langchain' 

### ISSUE THREAD

**Issue by madmudklip** [nextcloud/llm#3]
Nextcould AIO latest docker instance with LIM installed, configuration showing good
![Screenshot 2023-09-17 175612](https://github.com/nextcloud/llm/assets/78936546/74c9fc4a-366d-4827-bf51-2947bb7c8ac2)

Any task request through Nextcloud assistant results in the following error 

```
<html>
<body>
<!--StartFragment-->

Traceback (most recent call last): File "/var/www/html/custom_apps/llm/src-py/index.py", line 3, in <module> from chains.formalize import FormalizeChain File "/var/www/html/custom_apps/llm/src-py/chains/formalize.py", line 2, in <module> from langchain import BasePromptTemplate, PromptTemplate ModuleNotFoundError: No module named 'langchain' |  
-- | --


<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

I've confirmed that langchain is installed in the nextcloud container

![Screenshot 2023-09-17 175810](https://github.com/nextcloud/llm/assets/78936546/5e0f10a1-46ab-4584-bcf6-856cd02f1e22)

**Comment by marcelklehr** [comment]
> I've confirmed that langchain is installed in the nextcloud container

The app creates a virtual environment in which it tries to install the modules upon app installation. Could you try running occ maintenance:repair and check the nextcloud log for errors?

**Comment by marcelklehr** [comment]
Also, which version are you on (over here #912 people suggested a similar issue was fixed with the latest version)

**Comment by madmudklip** [comment]
@marcelklehr I'm on a fresh deployment of the latest version. Running maintenance:repair I'm seeing the follow error:

![Screenshot 2023-09-17 211446](https://github.com/nextcloud/llm/assets/78936546/e7b93789-e582-4dca-92e6-a290a31f1936)

**Comment by marcelklehr** [comment]
What architecture are you on? Which OS?

**Comment by madmudklip** [comment]
> What architecture are you on? Which OS?

This is a AIO docker instance running on X86 Ubuntu Server 22.04.3 LTS

**Comment by madmudklip** [comment]
Seems its a limitation with the container running in Alpine Linux as doesn't seem gpt4all 1.0.7 is available

**Comment by marcelklehr** [comment]
Ah, yes. See the requirements: https://github.com/nextcloud/llm#a-large-language-model-in-nextcloud
