### ISSUE TITLE
Other LLM's available, or are these hardcoded?

### ISSUE THREAD

**Issue by corsairius** [nextcloud/llm#58]
Brighteon.ai just added an LLM that supports GPT4all.  
This is a health-related LLM that would be interesting to add to an internal server.
Can this LLM or another be utilized by AI LLM?

**Comment by marcelklehr** [comment]
Hey @corsairius 

In this app the models are hardcoded. But we've since migrated the code to be fully based on python utilizing the External App Ecosystem. The new app is here: http://github.com/nextcloud/llm2
