### ISSUE TITLE
Better error handling when and documentantion for installing large language model

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/llm#6]
The app installs without errors even if packages like "python-venv" are missing.

After installing that I run into an dead end, because the server runs Debian stable which still uses Python 3.9:

```
Exception: Failed to install python dependencies: Failed to install python dependencies: PATH=/data/nextcloud/site/apps/llm/python/bin:$PATH VIRTUAL_ENV=/data/nextcloud/site/apps/llm/python POETRY_CACHE_DIR=/data/nextcloud/site/apps/llm/python/.cache /data/nextcloud/site/apps/llm/python/bin/poetry install --no-root returned Current Python version (3.9.2) is not allowed by the project (^3.10). Please change python executable via the "env use" command.
```

There are a lot of different server setups. Therefore a better documentation of requirements and more graceful error handling would be helpful.

**Comment by samssausages** [comment]
+1 to this.  I had a similar error, so I but python3.11-venv in my dockerfile, I no longer get the error, but it still doesn't work.  Better error reporting would help.

**Comment by marcelklehr** [comment]
> The app installs without errors even if packages like "python-venv" are missing.

This is not true. Check the nextcloud log

**Comment by ishaan-jaff** [comment]
Hi @marcelklehr @lars-becker @samssausages  I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
You can use our proxy server or spin up your own proxy server using LiteLLM**

## Usage
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# falcon call
response = completion(model="falcon-40b", messages=messages)
```

**Comment by marcelklehr** [comment]
The README documents to use python 3.10 now
