### ISSUE TITLE
Future musl support (Nextcloud AIO)

### ISSUE THREAD

**Issue by reayungao** [nextcloud/llm#9]
I love the idea of this project as it coule simplify rolling out AI features to Nextcloud.

I use Nextcloud-AIO and from what I understood, AIO uses musl instead of glibc (because Alpine Linux). I really want to roll out and play around with AI on my instance so would there be support for musl or something for this app to run natively on Nextcloud AIO?

Thank you for your wonderful work.

**Comment by marcelklehr** [comment]
Hey @reayungao 
Thank you for the kind words!
We are aware of the situation with AIO and are looking into ways to resolve it

**Comment by reayungao** [comment]
Thank you for the swift reply @marcelklehr! That's great to hear.

I really think this project will take off as I find it an easier solution than rolling out and configuring a LocalAI instance.

Keep up the great work.
